model:
  model_type: sparsevlm               
  model_path: liuhaotian/llava-v1.5-7b
  temperature: 0.0
  max_new_tokens: 16

  # SparseVLM specific          
  conv_mode: llava_v1              
runner:
  dataset: docvqa                   
  output_dir: ./outputs_eval        
  warmup: 3                       
  seed: 42